const praises = [
    "All of me loves all of you. Love your curves and all your edges, all your perfect imperfections\n - Jhon Legend",
    "Diante da vastidão do tempo e da imensidão do universo, é um imenso prazer para mim dividir um planeta e uma época com você.\n- Carl Sagan\nSérie: Cosmos",
    "Nenhum espaço de tempo com você seria suficiente... comecemos com o para sempre.\n Filme: Crepúsculo: Amanhecer Parte 1",
    "Eu adoro seu sorriso, seu sorri é... mágico.\n- Adam Sandler\nFilme: Esposa de mentirinha",
    "O teu riso é apaixonante. ❤️",
    "Já te disse como eu te amo?",
    "Quando eu olho para suas fotos, só consigo pensar uma coisa: eu namoro essa deusa. 😍",
    "Minha vontade é de te abraçar e nunca mais largar. 👩‍❤️‍💋‍👨",
    "A vida me deu a melhor pessoa do mundo como namorada.",
    "Você faz da minha vida um lugar bem melhor para se viver.",
    "Saber que você existe me motiva a acordar todas as manhãs.",
    "Se você fosse uma música seria as melhores notas\nFilme: O Amor Não Tira Férias.",
    "Eu amo a gente. Eu amo os nossos sonhos. Eu amo os nossos programas. Eu te amo. Você me fascina.",
    "Você me cativa. 🥰",
    "Amor, você virou a minha vida de cabeça para cima.",
    "Você chegou silenciosamente e transformou-me. Você é tão boa e tão especial que consegue até me fazer ser mais especial, só por estar do seu lado. ✨❤️",
    "Quando estou ao seu lado, sinto-me motivado a ser a minha melhor versão.",
    "Sempre sonhei em encontrar alguém especial na minha vida, mas você superou qualquer expectativa!",
    "Não me leve a mal, mas você arrasa com o meu pobre coração! 💘",
    "Queria que todas as pessoas no mundo tivessem esse grande coração que você tem.",
    "Eu olho suas fotos e fico hipnotizado pela sua beleza.",
    "É tão fácil te amar. 🥰❤️",
    "Ei, você, dona de uma beleza rara... Você arrasa com o meu coração.",
    "Sabe aquele belo azul do mar? E aquelas cores do arco-íris? E os tons do pôr do sol? Você é mais bela que tudo isso.",
    "Se você quer ser minha namorada\nAi, que linda namorada\nVocê poderia ser\nSe quiser ser somente minha\nExatamente essa coisinha\nEssa coisa toda minha\nQue ninguém mais pode ser\nVocê tem que me fazer um juramento\nDe só ter um pensamento\nSer só minha até morrer.\n- Vinicius de Moraes",
    "Esses olhos profundos e esse rosto fascinante: você é maravilhosa!",
    "Eu amo olhar o mundo por meio dos seus olhos! 🥰",
    "E, nos dias difíceis, você é a razão para eu não desistir.",
    "Eu sou o sortudo que ela escolheu para compartilhar a vida. 💖",
    "Ao seu lado, cada momento é único.",
    "O meu amor tem um jeito manso que é só seu, que rouba os meus sentidos, viola os meus ouvidos com tantos segredos lindos e indecentes…\n- Chico Buarque",
    "Você me deixa louco, menina linda!",
    "Às vezes te odeio por quase um segundo\ndepois te amo mais\nteus pelos, teu gosto, teu rosto, tudo\ntudo que não me deixa em paz.\n- Cazuza",
    "Eu te amo tanto que tenho vontade de te levar para todos os lados, avisando a todos que eu tive a sorte de finalmente te encontrar!",
    "Ela sorri com a alma, ela olha com o coração, ela abraça com o corpo todo. Ela é o meu amor maior. 😊",
    "Desde o primeiro dia que eu te conheci eu soube que você era a pessoa certa.",
    "É tão bom olhar para ti. 😊❤️",
    "Linda\nE sabe viver\nVocê me faz feliz\nEsta canção é só pra dizer\nE diz\nVocê é linda\nMais que demais\nVocé é linda sim\nOnda do mar do amor\nQue bateu em mim.\n- Caetano Veloso",
    "Você é a inspiração que move as minhas manhãs.",
    "De todas as pessoas incríveis desse mundo, eu tive sorte de encontrar a melhor de todas.",
    "Você é a mais bela flor desse jardim! 💐",
    "Você é o presente que sempre pedi para Deus.",
    "Eu tenho tanto pra te falar\nMas com palavras... Não sei dizer.\nComo é grande o meu amor por você.\n- Roberto Carlos",
    "Tenho tanta paixão por tudo o que você faz, pela forma como você enxerga o mundo, pelo seu jeito único de existir.",
    "A tua beleza me impressiona cada dia mais. ❤️",
    "Você foi a melhor coisa que já me aconteceu!",
    "O seu cheiro é melhor que o perfume de qualquer flor. 🌼",
    "O seu abraço é o melhor abraço do mundo.",
    "Para sempre. É para sempre que eu vou amar você. A cada dia que passa, tenho mais certeza da pessoa extraordinária que você é.",
    "O teu corpo é luz, sedução!\nPoema divino cheio de esplendor!\nTeu sorriso quente, inebria, entontece!\nÉs fascinação, amor!\n- Elis Regina",
    "Seus olhos são uma imensidão profunda que me fazem mergulhar em ti.",
    "Não há palavras que possam definir a sua beleza. Ela é única. 😊❤️",
    "Eu me apaixonei no momento que vi o seu sorriso pela primeira vez.",
    "Demorei muito pra te encontrar, agora eu quero só você. Teu jeito todo especial de ser, eu fico louco com você.\n- Fábio Jr.",
    "Seus olhos cheios de brilho são fascinantes. 😍",
    "Você é diferente de tudo o que eu já vi e vivi.",
    "Vontade de passar o dia a ouvir sua voz, só prestando atenção na sua beleza.",
    "Obrigado por me mostrar o que é o amor. Você ensinou-me o quão leve, fácil e belo ele é. Obrigado por trazer tranquilidade para a minha vida no lugar do caos.",
    "Olha essa mulher! É a dona do meu coração ❤️",
    "Eu pareço um bobo apaixonado... Por você.",
    "Menina linda eu quero morar na sua rua,\nVocê deixou saudade...\n- Chorão",
    "A magia mora ao seu lado. ✨",
    "Antes de te conhecer, eu estava insatisfeito com tantas coisas na minha vida... Você me ajudou a lidar com tudo e me fez evoluir. Obrigado!",
    "Você é o meu porto seguro, meu amuleto. Do seu lado, sempre está tudo bem.",
    "Às vezes, eu me pergunto se você é real ou se eu estou sonhando.",
    "Se tudo for um sonho, por favor não me acorde! Prefiro continuar sonhando com você na minha vida.",
    "É incrível como qualquer passeio com você parece a melhor coisa que eu já fiz na vida. 😊",
    "De todas as obras-primas da natureza, você é a maior delas! 🌺😍",
    "Eu juro, eu não te amo pouco, eu amo muito. Se quiser ouvir baixinho, vou falar no ouvidinho que eu te amo demais.\n- Ferrugem",
    "Quando eu te abraço, minha alma entra em profunda calmaria. 💞",
    "E as coisas lindas, são mais lindas quando você está.\n- Nando Reis",
    "Tem algo em você que eu nunca tinha visto antes. Não sei se é o brilho dos teus olhos, a tua força, a beleza do teu rosto, a alegria do teu sorriso... Talvez sejam todas essas coisas juntas. Eu te amo.",
    "A tua voz soa como música nos meus ouvidos. 🎵",
    "E longe de você é tudo mais ou menos.\nSe eu ganhar o mundo sem você, eu tô perdendo.\n- Matheus e Kauan",
    "Você não faz ideia de quantas vezes por dia eu agradeço o fato de você existir na minha vida.",
    "Eu adoro você exatamente do jeitinho que você é. 💝",
    "Gosto muito de te ver, leãozinho\nCaminhando sob o Sol\nGosto muito de você, leãozinho.\n- Caetano Veloso",
    "Eu preferiria compartilhar uma vida com você do que enfrentar todas as Eras do mundo sozinho.\n- J.R.R Tolkien",
    "Você é a pessoa que eu esperei a minha vida toda. 😍",
    "A sua energia é contagiante, o seu sorriso é magnífico e a sua beleza é inesquecível.",
    "Quando eu olho para você, só consigo pensar uma coisa: você é a pessoa certa.",
    "Você é a minha alma gêmea. 👩‍❤️‍💋‍👨",
    "Obrigado pelas conversas,\npela atenção,\npelo elogio que só vem de quem ama e,\nprincipalmente,\npor te importares comigo.\n- Augusto Branco",
    "Quando vejo a tua beleza só consigo pensar em como dei sorte.",
    "Você é sempre linda, mas hoje está deslumbrante. 🥰",
    "Você transformou a minha vida, sua maravilhosa!",
    "Escute o que eu tenho para lhe dizer, meu bem\nUm amor tão lindo igual a você não tem\nVou te proteger com o meu sentimento\nVai ficar suspenso o cheiro do nosso amor, no ar…\n- Raça Negra",
    "Sentir esse amor por ti é o melhor sentimento que já experienciei na vida.",
    "Linda e perfeita. 😛🥰💜",
    "Quando Deus te desenhou\nEle tava namorando\nQuando Deus te desenhou\nEle tava namorando\nNa beira do mar\nNa beira do mar, do amor.\n- Armandinho",
    "Com você, faço planos e não tenho medo de me arrepender.\n- Turma do Pagode",
    "A mulher da minha vida tem nome e um sobrenome bem ingrato.",
    "E se me perguntar qual é o seu defeito, ainda não sei. Te amo e nada mais...\n- João Neto e Frederico",
    "A sua inteligência e determinação me encantam.",
    "O que tem por trás desse sorriso, que me deixa fissurado em você.\n- Jorge e Mateus",
    "Você parece ter saído direto do cinema para minha vida.",
    "Eu gosto tanto de você, minha pequena. 🥰😘",
    "Você apaixonou, alucinou, descompassou meu coração.\n- Natiruts",
    "Corajosa, determinada e inteligente. Você não se cansa de ser tão incrível?",
    "Vejo tanta luz em ti. ✨",
    "Se eu não te amasse tanto assim\nTalvez não visse flores\nPor onde eu vi\nDentro do meu coração.\n- Ivete Sangalo",
    "Meu riso é tão feliz contigo\n O meu melhor amigo é o meu amor... \n- Velha Infância - Marisa Monte",
    "Parece tão certo estar contigo. Obrigado por me fazer tão feliz.",
    "Do teu lado, tudo ganha um novo sentido. 😍🥰",
    "Amo até os seus defeitos, imagine os beijos… \n- João Bosco e Vinicius",
    "Cada segundo do seu lado tem o valor de uma eternidade.",
    "Estranho seria se eu não me apaixonasse por você\n- Cássia Eller",
    "Você deixa o meu coração quente mesmo nos dias mais frios do ano.",
    "Com você, sinto-me em segurança. Sinto que posso confessar tudo, sinto que posso ser eu, sem qualquer medo. Obrigado.",
    "É tão bom ter do nosso lado uma pessoa que admiramos e amamos com todo o nosso coração. Essa pessoa é você, meu amor! ",
    "O coração dispara\nTropeça, quase para\nEu amei te ver\n- Tiago Iorc",
    "Você é a mais perfeita poesia.",
    "E eu acho que eu gosto mesmo de você… bem do jeito que você é!\n- Pitty",
    "De tantos oceanos que andei, ancorei em seu mar e viajei na sua praia. Você é água doce, no sal, que me sacia o paladar... O meu (a)mar.\n- Gil Buena"
]
function getPraise() {
    return praises[Math.floor(Math.random() * praises.length)] 
}