const txt = {
    $365: [
        'Eu amo o seu sorriso',
        'Eu amo os seus olhos',
        'Eu amo como você me entende.',
        'Eu amo seus carinhos',
        'Eu amo sua sinceridade',
        'Eu amo as suas piadas sem graça',
        'Eu amo as suas brincadeiras',
        'Eu amo o jeito que você fala comigo',
        'Eu amo a sua voz',
        'Eu amo os seus dentes',
        'Eu amo como você planeja o nosso futuro',
        'Eu amo como você esta em todos os meus planos',
        'Eu amo confiar em você',
        'Eu amo como você confia em mim',
        'Eu amo passar cada segundo do meu dia pensando em você',
        'Eu amo estar com saudade segundos depois de me despedir você',
        'Eu amo o seu cheiro',
        'Eu amo quando você para tudo e diz que me ama',
        'Eu amo quando mostra que sentiu saudades',
        'Eu amo o seu abraço',
        'Eu amo o seu beijo demorado',
        'Eu amo quando você tenta me irritar',
        'Eu amo a sua criatividade',
        'Eu amo a sua inteligência',
        'Eu amo o seu jeito bobo',
        'Eu amo nossas brincadeiras',
        'Eu amo quando você pensa que sou um sorvete hmmmm',
        'Eu amo como você me conforta',
        'Eu amo sua honestidade',
        'Eu amo a sua sobrancelha',
        'Eu amo quando você me provoca',
        'Eu amo a sua língua',
        'Eu amo ter você',
        'Eu amo ser seu',
        'Eu amo estralar suas costas',
        'Eu amo a sua beleza',
        'Eu amo te fazer rir',
        'Eu amo como você nunca me deixa triste',
        'Eu amo como sempre abro um sorriso quando te vejo',
        'Eu amo como depois de tanto tempo sou completamente apaixonado por você',
        'Eu amo ficar bobo com você',
        'Eu amo como você segura minha mão',
        'Eu amo como você arruma o cabelo',
        'Eu amo como você olha pra mim',
        'Eu amo cada segundo que eu passo contigo',
        'Eu amo falar as coisas que amo em você',
        'Eu amo a sua capacidade de me fazer rir em qualquer situação',
        'Eu amo quando você me aperta',
        'Eu amo quando você liga para mim',
        'Eu amo a sua ironia',
        'Eu amo a sua gargalhada',
        'Eu amo como você me respeita',
        'Eu amo quando me pede em casamento',
        'Eu amo quando você faz biquinho',
        'Eu amo sua  cara de ciúmes',
        'Eu amo como você é paciente comigo',
        'Eu amo como você é impaciente comigo',
        'Eu amo ser paciente com você',
        'Eu amo o seu romantismo',
        'Eu amo como você me tornou romântico',
        'Eu amo implicar com você',
        'Eu amo quando repara em mim',
        'Eu amo como te faço ficar sem argumentos',
        'Eu amo como você perde a linha',
        'Eu amo sua cara de bravinha',
        'Eu amo dormir nos teus braços',
        'Eu amo a segurança que você me transmite',
        'Eu amo deitar no teu colo',
        'Eu amo seu jeitinho atencioso comigo e com amigos',
        'Eu amo mexer no seu cabelo',
        'Eu amo bagunçar o seu cabelo',
        'Eu amo como você se preocupa mais com o cabelo do que com qualquer coisa',
        'Eu amo a sua demora pra se arrumar',
        'Eu amo a sua vaidade',
        'Eu amo a sua preocupação de ser linda pra mim',
        'Eu amo como você me ama até na TPM',
        'Eu amo como você tenta me entender',
        'Eu amo o seu jeito tímido',
        'Eu amo sonhar com você',
        'Eu amo quando você faz coisas que eu falo que eu amo',
        'Eu amo quando dorme comigo',
        'Eu amo quando você pede minha opinião',
        'Eu amo pedir sua opinião pra tudo',
        'Eu amo o fato de você ser uma completa gostosa',
        'Eu amo como você é o meu futuro',
        'Eu amo a nossa relação',
        'Eu amo seu pé',
        'Eu amo como você me acha bonito mesmo desarrumado',
        'Eu amo a sua coxa',
        'Eu amo os seus dedos',
        'Eu amo comer com você',
        'Eu amo sair com você',
        'Eu amo quando você admite seus erros',
        'Eu amo como você pede desculpa quando está errada',
        'Eu amo como você as vezes fala nada com nada',
        'Eu amo como nunca quero deixá-la ir',
        'Eu amo como odeio ficar longe de você',
        'Eu amo meu medo de te perder',
        'Eu amo sentir ciúme de você',
        'Eu amo como você me cuida',
        'Eu amo cuidar de você',
        'Eu amo te dar carinho',
        'Eu amo como você é tudo pra mim',
        'Eu amo ser seu tudo',
        'Eu amo o seu realismo',
        'Eu amo a sua esperança',
        'Eu amo o seu medinho',
        'Eu amo a capacidade que você tem de me fazer te amar intensamente',
        'Eu amo o nosso noivado',
        'Eu amo ser diferente com você',
        'Eu amo quando fala junto comigo a mesma coisa',
        'Eu amo a nossa fofura',
        'Eu amo quando batemos os dentes antes de beijar',
        'Eu amo como somos desastrados juntos',
        'Eu amo conhecer cada detalhe do seu corpo',
        'Eu amo como planejamos nosso futuro',
        'Eu amo como você quer estar comigo sempre',
        'Eu amo como você mudou por mim',
        'Eu amo como mudei por você',
        'Eu amo como perdemos nosso orgulho apenas para ficar bem',
        'Eu amo como a gente briga',
        'Eu amo como você sempre tem a forma mais fofa de fazer as coisas',
        'Eu amo te esquentar no frio',
        'Eu amo como você ronca quando tá cansadinha',
        'Eu amo seus vários tipos de beijo',
        'Eu amo o jeito como dorme',
        'Eu amo como nossa confiança nunca deixou abalar nosso relacionamento',
        'Eu amo como NADA abala nosso relacionamento',
        'Eu amo como você cuida de mim quando estou sensível',
        'Eu amo como você faz algo que você não goste só porque eu gosto',
        'Eu amo as musicas que você escuta (quase todas)',
        'Eu amo ser seu amor',
        'Eu amo como vamos ter uma menininha',
        'Eu amo como se veste',
        'Eu amo como com a gente é tudo intenso',
        'Eu amo como com a gente é tudo apaixonante',
        'Eu amo como com a gente é tudo fofo',
        'Eu amo quando você me manda mensagem no whatsapp mesmo eu estando ao seu lado',
        'Eu amo o jeito que me explica as coisas',
        'Eu amo a sua mensagem de boa noite',
        'Eu amo quando você me acorda com uma mensagem de bom dia',
        'Eu amo como você me dá um motivo para eu te amar mais todos os dias',
        'Eu amo como sempre conseguimos enfrentar tudo para ficar juntos',
        'Sua noiva ama quando ela consegue fazer uma surpresa para você e como vamos dormir juntinhos em uma casa na árvore',
        'Eu amo quando você se assusta',
        'Eu amo como nos assustamos',
        'Eu amo a sua mãe, sério!',
        'Eu amo dizer que te amo',
        'Eu amo como gosto de dizer que te amo toda hora',
        'Eu amo quando você diz que me ama em horas inesperadas',
        'Eu amo quando você faz algo inesperado',
        'Eu amo como você nunca é grosseira comigo',
        'Eu amo quando você faz surpresa',
        'Eu amo como odeio ganhar presente',
        'Eu amo seus presentes',
        'Eu amo o respeito que tem pelos meus pais',
        'Eu amo nossos assuntos',
        'Eu amo a nossa falta de assunto',
        'Eu amo como sempre que o silêncio chega, você me beija',
        'Eu amo quando você para de mexer no celular pra fazer vários nadas comigo',
        'Eu amo como você me beija',
        'Eu amo como você me deixa bravo de propósito',
        'Eu amo como você me impressiona',
        'Eu amo como você não precisa de esforço pra me impressionar',
        'Eu amo como você não precisa de esforço pra me fazer sorrir',
        'Eu amo como você não precisa de esforço pra me fazer feliz',
        'Eu amo como você consegue ser tudo o que preciso',
        'Eu amo precisar de você',
        'Eu amo quando acordo no meio da madrugada pensando em você',
        'Eu amo como meus pais gostam de você',
        'Eu amo como todo mundo gosta de você. Mas eu tenho ciúmes',
        'Eu amo como você consegue ser simpática com todo mundo',
        'Eu amo como você me trata diferente dos outros',
        'Eu amo como você fez eu confiar em você, para estar contigo até hoje',
        'Eu amo como você fez eu perder o medo de me entregar',
        'Eu amo como você é minha melhor amiga',
        'Eu amo a sua boca',
        'Eu amo como você se veste',
        'Eu amo o seu estilo',
        'Eu amo como você me olha',
        'Eu amo amar tudo em você',
        'Eu amo reparar nos seus detalhes',
        'Eu amo de perceber o seu jeito',
        'Eu amo como você faz meu olho brilhar',
        'Eu amo como você faz meu coração bater mais depressa',
        'Eu amo como quando estou com você o tempo passa rápido',
        'Eu amo como quando estou com você o tempo passa devagar',
        'Eu amo como você me faz rir sozinho',
        'Eu amo seu jeito protetor',
        'Eu amo como você faz eu me sentir um homem',
        'Eu amo quando você me dá a certeza de que me ama',
        'Eu amo quando você me dá a certeza de que sou único',
        'Eu amo quando você me dá a certeza de que viveremos sempre felizes',
        'Eu amo sua respiração',
        'Eu amo seu ouvido',
        'Eu amo sua respiração nas ligações',
        'Eu amo como você morde os lábios',
        'Eu amo como você me acaricia',
        'Eu amo sua mão',
        'Eu amo o seu queixo',
        'Eu amo a sua bochecha',
        'Eu amo receber uma mensagem sua na Alexa',
        'Eu amo como você não se expressa',
        'Eu amo seu modo de falar',
        'Eu amo a sua letra',
        'Eu amo o som da sua risada',
        'Eu amo o NOSSO dia 27 🤩❤️', // 27 pra dar uma de doido 😈🤪🤪🤪
        'Eu amo como esse é o primeiro dia de mais um ano com você 🥰',
        'Eu amo como você é MINHA NOIVA 😍❤️',
        'Eu amo os seus defeitos',
        'Eu amo seu pé',
        'Eu amo todas as partes do seu corpo',
        'Eu amo a sua alegria',
        'Eu amo a sua carência',
        'Eu amo como você ama ouvir eu explicar',
        'Eu amo quando começo as dizer as coisas que mais amo em ti, e você fica falando o que ama em mim também',
        'Eu amo o seu sorriso após o beijo demorado',
        'Eu amo as suas manias',
        'Eu amo como você me contagia com sua alegria',
        'Eu amo como me sinto mal, quando te vejo triste',
        'Eu amo a cor dos seus olhos',
        'Eu amo quando você diz que me ama olhando pra mim',
        'Eu amo o brilho dos seus olhos',
        'Eu amo quando você tira o cabelo do olho',
        'Eu amo quando você beija minha testa',
        'Eu amo quando você me corrige',
        'Eu amo te corrigir',
        'Eu amo beijar sua testa',
        'Eu amo nossa amizade',
        'Eu amo quando você se rende a mim',
        'Eu amo a sua educação',
        'Eu amo como você me conhece',
        'Eu amo como você repara em pequenos detalhes meus',
        'Eu amo te fazer feliz',
        'Eu amo ser seu noivo',
        'Eu amo quando você beija minha barriga',
        'Eu amo como você me mima',
        'Eu amo como você cuida da nossa relação',
        'Eu amo como você se acha bonita',
        'Eu amo quando deita no meu colo',
        'Eu amo me sentir sortudo por ter você',
        'Eu amo escolher a cor do meu esmalte',
        'Eu amo quando diz que não vai me abandonar',
        'Eu amo sua personalidade forte e marcante',
        'Eu amo como você pretende criar um zoológico comigo',
        'Eu amo quando cozinha para mim',
        'Eu amo sua responsabilidade',
        'Eu amo o fato de você demorar a tomar banho',
        'Eu amo sua perfeição',
        'Eu amo sua mordida',
        'Eu amo seus carinhos brutos',
        'Eu amo a nossa aliança',
        'Eu amo as suas perguntas',
        'Eu amo as suas respostas',
        'Eu amo as suas ideias loucas',
        'Eu amo quando você ouve com minhas ideias loucas',
        'Eu amo quando você faz algo, só porque eu disse amar tal coisa',
        'Eu amo a nossa imaginação',
        'Eu amo viajar em pensamentos com você',
        'Eu amo o seu sorriso',
        'Eu amo seu beijo delicado',
        'Eu amo seu beijo ardente',
        'Eu amo seu beijo carinhoso',
        'Eu amo seu beijo brincalhão',
        'Eu amo quando você me dá comida na boca',
        'Eu amo a massagem perfeita que faz',
        'Eu amo o modo como  transforma uma hora péssima em perfeição!',
        '99-Quando me dá um “chêro”',
        'Eu amo quando você é otimista',
        'Eu amo como sempre me faz chorar',
        'Eu amo como você faz eu me sentir a vontade',
        'Eu amo como você me belisca',
        'Eu amo te beliscar',
        'Eu amo te apertar',
        'Eu amo o nosso jeito “criança”',
        'Eu amo o nosso jeito “maduro”',
        'Eu amo o nosso jeito ”foda”',
        'Eu amo o jeito que você anda',
        'Eu amo andar de mãos dadas contigo',
        'Eu amo como aprendi a ser melhor contigo',
        'Eu amo o seu abraço apertado',
        'Eu amo mexer no seu nariz',
        'Eu amo como nossas mãos se encaixam',
        'Eu amo como meu corpo se encaixa perfeitamente ao teu',
        'Eu amo quando você esta tímida',
        'Eu amo quando você tenta fingir que está brava',
        'Eu amo quando você briga comigo, quando eu te deixo muito tempo esperando',
        'Eu amo te fazer ficar brava, só pra ver sua carinha',
        'Eu amo sua cara de sono',
        'Eu amo sua cara de safada',
        'Eu amo te xingar',
        'Eu amo o jeito que falamos do futuro',
        'Eu amo quando você me liga de manhã',
        'Eu amo quando você me liga apenas para dormir',
        'Eu amo quando me liga',
        'Eu amo como você faz tudo ficar bem',
        'Eu amo dormir pensando em você',
        'Eu amo acordar pensando em você',
        'Eu amo pensar em você',
        'Eu amo sonhar com você',
        'Eu amo quando você torna um sonho meu em realidade kkk',
        'Eu amo te admirar',
        'Eu amo como você me serve de exemplo',
        'Eu amo servir de exemplo pra você',
        'Eu amo como você me admira',
        'Eu amo como você me elogia',
        'Eu amo como pensamos até nos detalhes do nosso futuro',
        'Eu amo como imaginamos',
        'Eu amo como calculamos o nosso futuro',
        'Eu amo como tudo acontece naturalmente',
        'Eu amo ser eu mesmo contigo',
        'Eu amo quando você sussurra em meu ouvido',
        'Eu amo ouvir você dizendo “amor”',
        'Eu amo como você joga no celular comigo',
        'Eu amo como você se preocupa comigo',
        'Eu amo me preocupar com você',
        'Eu amo quando você pede para ir a algum lugar',
        'Eu amo quando você faz birrinha',
        'Eu amo você ser o AMOR DA MINHA VIDA',
        'Eu amo ser o AMOR DA SUAS VIDAS',
        'Eu amo conversar com você no Whatsapp',
        'Eu amo passar mais de uma hora no telefone com você',
        'Eu amo os apelidos carinhosos que você coloca em mim',
        'Eu amo ter esperança que você ira me dar uma sandália da Prada',
        'Eu amo como existem N motivos para eu te amar',
        'Eu amo como você faz eu me sentir vivo',
        'Eu amo você ser MINHA (tóxico mesmo)',
        'Eu amo quando eu falo demais, e mesmo assim você me ouve com atenção',
        'Eu amo ter importância na sua vida',
        'Eu amo você ter total importância na minha vida',
        'Eu amo o nosso amor não ter medidas',
        'Eu amo seus pais',
        'Eu amo como seu coração acelera quando fala sobre coisas sérias',
        'Eu amo como nosso amor pode preencher o universo',
        'Eu amo como se dividir o nosso amor para todos os casais que existem no mundo, ainda assim, ele seria mais que o suficiente',
        'Eu amo como você é mais do que eu esperava pra ser "o amor da minha vida"',
        'Eu amo como nunca encontro palavras pra expressar esse sentimento',
        'Eu amo te querer',
        'Eu amo quando ia pra escola, apenas pra ver você',
        'Eu amo quando dizem que somos bonitinhos juntos',
        'Eu amo ter mudado por você',
        'Eu amo não precisar viver sem você',
        'Eu amo você ter aparecido no momento em que eu mais precisei',
        'Eu amo a certeza de que você nunca irá me perder',
        'Eu amo a segurança de que vou te ter sempre comigo',
        'Eu amo pensar em você antes de comprar alguma coisa que você gosta',
        'Eu amo como você é minha inspiração',
        'Eu amo nossas fotos',
        'Eu amo quando você faz bilhetinho pra mim no curso',
        'Eu amo como durante esse tempo juntos, eu não tive dúvida, sequer um dia, se é realmente você, que e quero pra toda minha vida',
        'Eu amo como minha necessidade de você aumenta conforme o tempo que passamos juntos',
        'Eu amo saber que nosso amor é sincero',
        'Eu amo saber que nosso amor não é frágil',
        'Eu amo saber que vamos conseguir enfrentar tudo',
        'Eu amo cada detalhe seu',
        'Eu amo como meu coração é apenas seu',
        'Eu amo ter a certeza que você é o "Amor da minha vida"',
        'Eu amo como você me fez acreditar no amor',
        'Eu amo como nosso amor não tem sentido',
        'Eu amo como você se destaca',
        'Eu amo como você é diferente de qualquer outra',
        'Eu amo como você é minha, muito minha',
        'Eu amo como sou grato por tudo que você faz e fez por mim até hoje',
        'Eu amo como com você eu me sinto capaz de qualquer coisa',
        'Eu amo você, apenas por ser você, sem precisar de motivos ou um porquê. Isso não tem explicação, não tem definição, é amor ou talvez mais que isso. É intenso, é puro, é real... Eu amo cada detalhe seu.',
    ],
    phraseOfMusic: [
        " Você é algo assim, é tudo pra mim, é como eu sonhava, baby! \n- Tim Maia",
        " I have loved you for a thousand years... \nI'll love you for a thousand more. \n(Eu te amei por mil anos... Eu te amarei por mais mil.) \n- Christina Perri",
        " Como que eu vou dizer pra ela, que eu gosto do seu cheiro, da cor do seu cabelo, que ela faz minha pupila dilatar. \n- Anavitória e Vitor Kley",
        " Amor da minha vida daqui até a eternidade, nossos destinos foram traçados na maternidade. \nCazuza",
        " And I will always love you! \n(E eu sempre vou te amar!) \n- Whitney Houston",
        " I'm thinking out loud and maybe we found love right where we are. \n(Estou pensando alto e talvez nós tenhamos encontrado o amor bem onde nós estamos.) \n- Ed Sheeran ",
        " When you look me in the eyes and tell me that you love me, everything's all right. \n(Quando você me olha nos olhos e diz que me ama, tudo fica bem.) \n- Jonas Brothers",
        " Eu sei que vou te amar. \nPor toda a minha vida eu vou te amar. \nEm cada despedida eu vou te amar. \nDesesperadamente, eu sei que vou te amar! \n- Tom Jobim",
        " My first love, you're every breath that I take, you're every step I make. \n(Meu primeiro amor, você é todo respiro que eu dou, você é cada passo que eu dou.) \n- Lionel Richie",
        " É você que é o homem meu, meu grande amor da minha vida. \n- Mallu Magalhães",
        " Estranho seria se eu não me apaixonasse por você! \n- Nando Reis",
        " Eu troco minha paz por um beijo seu, eu troco meu destino pra viver o seu. \nEu troco minha cama pra dormir na sua, eu troco mil estrelas pra te dar a Lua e tudo que você quiser. \nE se você quiser, te dou meu sobrenome! \n- Luan Santana ",
        " Vai se entregar pra mim, como a primeira vez... \nVai delirar de amor, sentir o meu calor, vai me pertencer! \n- Paula Fernandes ",
        " Todo mundo tem uma pessoa, aquela pessoa que te faz esquecer todas as outras. \n- Henrique e Juliano ",
        " Ainda sou o mesmo bobo apaixonado, se eu estou errado, não quero nem saber. \nEu só sei que a vida é mais colorida com você! \n- Jorge e Mateus ",
        " Tantos sorrisos por aí, você querendo o meu... \nTantos olhares me olhando e eu querendo o seu. \nEu não duvido, não, que não foi por acaso, se o amor bateu na nossa porta, que sorte a nossa! \n- Matheus e Kauan ",
        " Vamos fazer assim, eu cuido de você, você cuida de mim... \nNão desisto de você e nem você de mim, vamos até o fim! \n- Lucas Lucco ",
        " Mas a verdade é que eu sou louco por você e tenho medo de pensar em te perder... \nEu preciso aceitar que não dá mais pra separar as nossas vidas. \n- Chitãozinho e Xororó ",
        " Na linha do tempo \nO destino escreveu \nCom letras douradas \nVocê e eu. \n- Victor e Leo ",
        " Eu não te amo como ontem, amo mil vezes mais! \n- João Neto e Frederico ",
        " Se der um sorriso não vou resistir, sua boca dizendo 'te quero pra mim', que me esperou, que tava com saudade, amor! \n- Thaeme e Thiago ",
        " Eu te amo, é paixão que não tem fim... \nDou a vida por um beijo, quero ter você pra mim! \n- Zezé Di Camargo e Luciano ",
        " Cause you're all I need... \n(Porque você é tudo que eu preciso...) \n- Sam Smith ",
        " 'Cause all of me loves all of you! \n(Porque tudo em mim ama tudo em você!) \n- John Legend ",
        " Love me like you do! \n(Me ame como só você faz!) \n- Ellie Goulding ",
        " You're every line, you're every word, you're everything! \n(Você é cada frase, você é cada palavra, você é tudo!) \n- Michael Bublé ",
        " And when you smile the whole world stops and stares for a while, cause, girl, you're amazing just the way you are! \n(E quando você sorri, o mundo inteiro para e fica olhando por um tempo, pois, garota, você é incrível do jeito que você é!) \n- Bruno Mars ",
        " I keep you with me in my heart. \nYou make it easier when life gets hard. \n(Te guardo comigo em meu coração. Você torna as coisas fáceis quando a vida fica difícil.) \n- Jason Mraz ",
        " You bless me with the best gift that I've ever known... \nYou give me purpose! \n(Você me abençoa com o melhor presente que eu já vi... Você me dá propósito!) \n- Justin Bieber ",
        " I don't know who I am without you. \n(Não sei quem eu sou sem você.) \n- Demi Lovato ",
        " I can't take my mind off you! \n(Não consigo parar de pensar em você!) \n- Damien Rice ",
        " Baby, it's you... \nYou're the one I love, you're the one I need, you're the only one I see! \n(Amor, é você... Você é aquele que eu amo, você é aquele que eu preciso, você é o único que eu vejo!) \n- Beyoncé ",
        " You came and breathed new life into this lonely heart of mine... \nYou threw out the life line just in the nick of time! \n(Você chegou e trouxe uma vida nova para meu coração solitário... \nVocê me salvou na hora certa!) \n- Brian McKnight ",
        " Something about you now I can't quite figure out... \nEverything she does is beautiful... \nEverything she does is right! \n(Existe algo sobre você agora que não consigo compreender completamente. Tudo o que ela faz é bonito... Tudo o que ela faz é certo!) \n- Lifehouse ",
        " Well, I found a woman stronger than anyone I know... \nShe shares my dreams, I hope that someday I'll share her home. \n(Bem, eu encontrei uma mulher mais forte que qualquer uma que eu conheço... Ela compartilha meus sonhos, eu espero que um dia eu compartilhe seu lar.) \n- Ed Sheeran ",
        "Meu riso é tão feliz contigo \nO meu melhor amigo é o meu amor... \nVelha Infância - Marisa Monte",
        "Porque um joelho ralado \nDói bem menos que um coração partido \nEra uma Vez - Kell Smith",
        "Congela o teu olhar no meu \nEsconde que já percebeu \nQue todo meu amor é teu amor \nFica - Anavitória (Part. Matheus & Kauan)",
        "Ela une o mar Com o meu olhar \nEla só precisa existir \nPra me completar \nEla Une Todas as Coisas - Jorge Vercillo",
        "Me perdi no seu sorriso, nem preciso me encontrar. \nMina do Condomínio - Seu Jorge",
        "Me dê a mão, e vamos por aí, não pense em nada agora que já passou da hora, eu quero tanto te fazer sorrir. \nCosta Verde - Forfun",
        "O coração dispara Tropeça, quase para \nEu amei te ver \nAmei te Ver - Tiago Iorc",
        "Com amor se paga amor \nE o ditado é quem diz \nQue a gente ama assim sem dar desconto \n- Feliz e Ponto - Silva",
        "Vamos ver um filme, ter dois filhos \nIr ao parque discutir Caetano \nPlanejar bobagens e morrer de rir \nVagalumes Cegos - Cícero",
        "Só sei dançar com você \nIsso é o que o amor faz \nSó Sei Dançar Com Você - Tulipa Ruiz",
        "Hoje ninguém vai estragar meu dia,\nSó vou gastar energia pra beijar sua boca \n- Céu Azul - Charlie Brown Jr.",
        "E eu acho que eu gosto mesmo de você… bem do jeito que você é! \nPitty - Equalize",
        "É você que é o homem meu \nMeu grande amor da minha vida \n- É Você que Tem - Mallu Magalhães",
        "Se eu não te amasse tanto assim \nTalvez não visse flores \nPor onde eu vi dentro do meu coração \nSe Eu Não Te Amasse Tanto Assim - Ivete Sangalo",
        "Não conheci o amor, só conhecia a bondade. \nE hoje conheci você, e é amor de verdade. \n- Nosso Amor - MC Pedrinho",
        "Se é amor, sei lá, só sei que sem você parei de respirar. \nQuando Você Passa - Sandy e Junior",
        "É, e na hora que eu te beijei \nFoi melhor do que eu imaginei \nSe eu soubesse tinha feito antes \nNo fundo sempre fomos bons amantes \nMedo Bobo - Maiara e Maraisa",
        "Já era amor antes de ser \nJá era seu antes do sim \nJá era nós antes que eu pudesse escolher \nEu te encontrei e me perdi \nEu permiti acontecer, aconteceu sem avisar \nIsso que é amar \nHenrique e Juliano - Vida",
        "A gente se conheceu há pouco tempo \nMas a gente já está falando em casamento \nTô correndo um risco sério de viver pra sempre com você\nPra sempre com você - Jorge e Mateus",
        "O que falta em você sou eu \nSeu sorriso precisa do meu \nSei que tá morrendo de saudade \nVem buscar logo a sua metade\nO Que Falta Em Você Sou Eu - Marília Mendonça",
        "Nosso amor não tem segredos, sabe tudo de nós dois e joga fora nossos medos\n- Talismã - Leandro e Leonardo",
        "Não quero ser precipitado, muito menos te assustar. \nMas é nesse teu sorriso que o meu beijo quer morar\nContramão - Gustavo Mioto",
        "Resolve esse impasse \nE assuma pra gente, essa louca paixão \nMe abraça e me beija \nQue eu tomo conta de você\nImpasse - Marília Mendonça (Part. Henrique e Juliano)",
        "Tantos sorrisos por aí, você querendo o meu \nTantos olhares me olhando e eu querendo o seu \nEu não duvido não, que não foi por acaso \nSe o amor bateu na nossa porta, que sorte a nossa\nQue Sorte a Nossa - Matheus e Kauan",
        "Seu amor foi sempre muito mais \nDo que eu sonhei pra mim \nSempre mais do que eu mereci \nPensa direito antes de dormir \nE sonha comigo\nSonha Comigo - Zé Neto e Cristiano",
        "E perto um do outro, a vida é diferente a solidão dá espaço ao amor que estava ausente, quem olha não tem jeito de duvidar agora da força da paixão que tem dois corações e uma história…\nDois Corações e Uma História - Zezé Di Camargo e Luciano",
        "Eu troco minha paz por um beijo seu \nEu troco meu destino pra viver o seu \nEu troco minha cama pra dormir na sua \nEu troco mil estrelas pra te dar a lua \nE tudo que você quiser \nE se você quiser te dou meu sobrenome\nTudo que Você Quiser - Luan Santana",
        "Eu acho que a gente se apaixonou \nE o beijo da gente me viciou \nParece que a gente já tá dependente um do outro \nIsso é amor\nDependente - Sorriso Maroto",
        "Quero ter você, custe o que custar, pela vida inteira\nPela Vida Inteira - Jeito Moleque",
        "E por mais que você me deixe no futuro \nVale o risco, eu juro, nunca amei ninguém assim \nAté você de mal faz bem pra mim\nGuerra Fria - Sorriso Maroto (Part. Jorge e Matheus)",
        "Ainda bem que te encontrei \nAgora sou mais feliz, igual não tem \nMe trata bem do jeito que eu sempre quis\nAinda bem - Thiaguinho",
        "E agora meu mundo é seu mundo \nSeu corpo em meu corpo é um só \nÉ um sentimento maior.\nComo Nunca Amei Ninguém - ExaltaSamba",
        "Meu coração está radiante, \nBate feliz acho que é o amor, \nQuando te vejo chego a sonhar.\nCoração Radiante - Grupo Revelação",
        "Escute o que eu tenho para lhe dizer, meu bem \nUm amor tão lindo igual a você não tem \nVou te proteger com o meu sentimento \nVai ficar suspenso o cheiro do nosso amor, no ar…\nDoce Paixão - Raça Negra",
        "Me dê uma chance posso te mostrar Que o meu amor não vai te machucar E tudo que eu mais quero nessa vida é você O que sentimos não dá pra esconder E nunca mais vai ter fim Acredita em mim, acredita em nós, de novo\nSei que é você - Onze: 20",
        "Hoje pensei tanto em nós dois Que não podia deixar pra depois E eu vim aqui só pra dizer Que eu sou louco por você.\nApenas Uma Canção de Amor - Rosa de Saron",
        "Me sinto tão amada, isso faz bem Ao coração da gente quando tem Alguém pra dividir um grande amor Como a brisa da manhã, assim você chegou\nQue bom Você Chegou - Bruna Karla",
        "Só você é a dona do meu coração Razão que causa a minha emoção A lógica do meu grande amor é você Só você pra preencher a minha canção Piano e voz só foi uma questão O que eu queria mesmo é ter só pra mim a tua atenção\nSó Você - Anderson Freire",
        "E passe o tempo que passar O meu amor foi feito pra durar Em meios aos espinhos, passo junto com você Te amo mais do que posso descrever.\nTudo que sonhei - Cristina Mel",
        "Vi que era amor quando te achei em mim e me perdi em você.\nDois Corações - Melim",
        "Meu amor não será passageiro Te amarei de Janeiro a Janeiro Até o mundo acabar\nDe Janeiro a Janeiro - Nando Reis",
        "E longe de você é tudo mais ou menos. Se eu ganhar o mundo sem você, eu tô perdendo\nMágica - Matheus e Kauan",
        "Me namora, pois quando eu saio eu sei que você chora E fica em casa só contando as horas Reclama só do tempo que demora Abre os braços vem e me namora\nMe Namora - Natiruts",
        "Por onde andei Enquanto você me procurava?\nPor Onde Andei - Nando Reis",
        "Heaven is a place on earth with you.(O paraíso é um lugar na terra com você.)\nVideo Games - Lana Del Rey",
        "You're my end and my beginning Even when I lose I'm winning 'Cause I give you all of me And you give me all of you(Você é o meu fim e meu começo Mesmo quando perco estou ganhando Porque te dou tudo de mim E você me dá tudo de você)\nAll of Me - John Legend",
        "And when you smile The whole world stops and stares for a while 'Cause girl you're amazing Just the way you are(E quando você sorri O mundo inteiro para e fica olhando por um tempo Pois, garota, você é incrível Exatamente como você é)\nJust the Way You Are - Bruno Mars",
        "Take my hand, take my whole life too. For I can't help falling in love with you.(Pegue minha mão, pegue minha vida inteira também. Porque eu não posso deixar de me apaixonar por você.)\nCan't Help Falling in Love - Elvis Presley",
        "Kiss me under the light of a thousand stars Place your head on my beating heart I'm thinking out loud Maybe we found love right where we are(Beije-me sob a luz de mil estrelas Coloque sua cabeça no meu coração batendo Estou pensando em voz alta Talvez tenhamos encontrado amor exatamente onde estamos)\nThinking Out Loud - Ed Sheeran",
        "A minha felicidade está sonhando Nos olhos da minha namorada É como esta noite, passando, passando Em busca da madrugada\nA Felicidade - Vinicius de Moraes",
        "Amor da minha vida, daqui até a eternidade. Nossos destinos foram traçados na maternidade\nExagerado - Cazuza",
        "O teu corpo é luz, sedução! Poema divino cheio de esplendor! Teu sorriso quente, inebria, entontece! És fascinação, amor!\nFascinação - Elis Regina",
        "E até quem me vê lendo o jornal Na fila do pão, sabe que eu te encontrei E ninguém dirá que é tarde demais Que é tão diferente assim Do nosso amor a gente é que sabe, pequena\nÚltimo Romance - Los Hermanos",
        "Eu sou sua menina, viu? E ele é o meu rapaz. Meu corpo é testemunha do bem que ele me faz.\nO Meu Amor - Chico Buarque",
        "Antes de mais nada, eu te amo Desculpa me apressar mas Tava engasgado, eu tinha que desabafar\nO Vento - Projota",
        "Ah, minha linda Eu te amo Ah, meu Deus Como eu te quero Onde 'cê tiver eu vou Você sabe que é sincero\nComo Eu Te Quero - Black Alien",
        "Tenho você por perto Nunca me senti tão completo Nunca me senti tão seguro Perco o medo do fim do mundo\nPlanos - BK'",
        "Eu gosto tanto dela, A ponto de querer 'tá perto, pronto Não tem outro jeito de me ver sorrir É louco o efeito dela, aqui\nEu gosto dela - Emicida",
        "Antes de mais nada, eu te amo \nDesculpa me apressar mas \nTava engasgado, eu tinha que desabafar\nO Vento - Projota",
        "Tenho você por perto \nNunca me senti tão completo \nNunca me senti tão seguro \nPerco o medo do fim do mundo\nPlanos - BK'",
        "Eu gosto tanto dela, \nA ponto de querer 'tá perto, pronto \nNão tem outro jeito de me ver sorrir \nÉ louco o efeito dela, aqui\nEu gosto dela - Emicida",
        "Lá fora o mundo desmorona \nA maldade do mundo te fez ser durona \nTe amo mais do que me amo, sei que é cafona \nO amor é uma viagem, valeu pela carona.\nTão Moleque - Projota",
    ],
    getRandomTxt: (e) => {
        return e[Math.floor(Math.random() * e.length)]
    }
}